name: Gardnerlaundromat
favicon: null
layout_spectrum: 0.15838684258051217
typography_spectrum: 0.5605694258119911
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ddecf6'
    - '#1c9ad5'
    - '#00468e'
    - '#000000'
    - '#00ffff'
  brandStrength: 0.7201983737759292
  lightness: 0.6086363543290645
  saturation: 0.3113556541502476
  rhythmicContrast: 0.6233633081428707
purpose: []
